site_name: {{cookiecutter.component_id | jsonify}}
site_description: {{cookiecutter.description | jsonify}}

nav:
  - Overview: index.md
  - How To: howto.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md

plugins:
  - techdocs-core
