apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: v1beta2-demo
  title: Test Action template
  description: scaffolder v1beta2 template demo publishing to github
spec:
  owner: DmitriyKhirniy
  type: website

  parameters:
    - title: Fill in some steps
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        graphql_client:
          title: Use GraphQL client
          type: string
          enum: [ 'yes', 'no' ]
          description: Include GraphQL client with an example
          default: 'yes'
        collaborators:
          title: Collaborators
          description: Provide users with permissions
          type: array
          ui:options:
            orderable: false
          items:
            type: object
            required:
              - username
              - access
            properties:
              access:
                type: string
                description: The type of access for the user
                default: pull
                enum:
                  - push
                  - pull
                  - admin
                  - maintain
                  - triage
              username:
                type: string
                description: The username or group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        url: https://github.com/DmitriyKhirniy/code-templates/tree/main/angular-template-old/template
        values:
          name: '{{ parameters.name }}'
          owner: '{{ parameters.owner }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
          graphql_client: '{{ parameters.graphql_client }}'
          repoUrl: '{{ parameters.repoUrl }}'

    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./community
        url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is {{ parameters.name }}'
        repoUrl: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
    collaborators: '{{ parameters.collaborators }}'
