apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: customDimaAngularTemplate
  title: Custom Dima Angular template
  description: scaffolder v1beta2 template demo publishing to github Angular app new
spec:
  owner: DmitriyKhirniy
  type: website

  parameters:
    - title: Fill in some steps
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
#          type: string
          description: Owner of the component
          type: string
          enum: [ 'Galileo-Backstage', 'GalileoDigital' ]
          default: 'Galileo-Backstage'
         # ui:field: OwnerPicker
#          ui:options:
#            allowedKinds:
#              - Group

        graphql_client:
          title: Use GraphQL client
          type: string
          enum: [ 'yes', 'no' ]
          description: Include GraphQL client with an example
          default: 'yes'
        collaborators:
          title: Collaborators
          description: Provide users with permissions
          type: array
          ui:options:
            orderable: false
          items:
            type: object
            required:
              - username
              - access
            properties:
              access:
                type: string
                description: The type of access for the user
                default: pull
                enum:
                  - push
                  - pull
                  - admin
                  - maintain
                  - triage
              username:
                type: string
                description: The username or group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        url: https://github.com/DmitriyKhirniy/code-templates/tree/main/angular-template-old/skeleton
        values:
          name: '{{ parameters.name }}'
          owner: '{{ parameters.owner }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
          graphql_client: '{{ parameters.graphql_client }}'
          repoUrl: '{{ parameters.repoUrl }}'

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is {{ parameters.name }}'
        repoUrl: '{{ parameters.repoUrl }}'
        collaborators: '{{ json parameters.collaborators }}'

    - id: customAction
      name: Configure Github repository
      action: galileo-digital:create-file
      input:
        contents: 'custom content by dima'
        filename: 'custom_file.text'
        repoUrl: '{{ parameters.repoUrl }}'
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        #repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        repoContentsUrl: '{{ steps.customActions.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
