apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: angular-single-spa-template-v1
  title: Angular SingleSpa Template V1
  description: Create a microfrontend app with angular and single spa library
  tags:
    - recommended
    - angular
    - singlespa
spec:
  owner: web@example.com
  templater: cookiecutter
  type: website
  path: '.'
  schema:
    required:
      - component_id
      - description
      - graphql_client
    properties:
      component_id:
        title: Name
        type: string
        pattern: ^[a-z0-9]+(-[a-z0-9]+)*$
        description: Unique name of the component. Lowercase, URL-safe characters only.
      description:
        title: Description
        type: string
        description: Help others understand what this website is for.
      graphql_client:
        title: Use GraphQL client
        type: string
        enum: [ 'yes', 'no' ]
        description: Include GraphQL client with an example
        default: 'yes'
      collaborators:
        title: Collaborators
        description: Provide users with permissions
        type: array
        ui:options:
          orderable: false
        items:
          type: object
          required:
            - username
            - access
          properties:
            access:
              type: string
              description: The type of access for the user
              default: pull
              enum:
                - push
                - pull
                - admin
                - maintain
                - triage
            username:
              type: string
              description: The username or group
