apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: angular-microfrontend-single-spa-template5
  title: Angular SingleSpa Template Custom5
  description: Create a microfrontend app with angular and single spa
  tags:
    - recommended
    - angular
    - singlespa
spec:
  owner: web@example.com
  templater: cookiecutter
  type: website
  path: '.'
  schema:
    required:
      - project_name
      - project_description
      - graphql_client
    properties:
      project_name:
        title: Name
        type: string
        description: Unique name of the component
      project_description:
        title: Description
        type: string
        description: Help others understand what this website is for.
      graphql_client:
        title: Use GraphQL client
        type: string
        enum: [ 'true', 'false' ]
        description: Include GraphQL client with an example
        default: 'true'
